export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import DashboardIcon from "@mui/icons-material/Dashboard";
import ContactsIcon from "@mui/icons-material/Contacts";
import HealthAndSafetyIcon from "@mui/icons-material/HealthAndSafety";
import LogoutIcon from "@mui/icons-material/Logout";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="row">
          <div className="col-md-2">
            {/* Left-side Navbar */}
            <nav className="admin-sidebar">
              <ul>
                <li className="mb-5 mt-0">
                  <a href="#">
                    <img
                      src="/images/logo.png"
                      alt="all good financial services"
                      height="60px"
                    />
                  </a>
                </li>
                <li>
                  <DashboardIcon />
                  <a href="#">
                    <b>Dashboard</b>
                  </a>
                </li>
                <li>
                  <ContactsIcon />
                  <a href="#contacts">
                    <b>Contact Forms</b>
                  </a>
                </li>
                <li>
                  <HealthAndSafetyIcon />
                  <a href="#insurance-forms">
                    <b>Health Insurance Forms</b>
                  </a>
                </li>
                <div className="logout-container">
                  <li className="logout">
                    <LogoutIcon />
                    <a href="#insurance-forms">
                      <b>Logout</b>
                    </a>
                  </li>
                </div>
              </ul>
            </nav>
          </div>
          <div className="col-md-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
